import { ERPsportDTO, IUserRegistrDTO, OrganizationDTO, UserApplicationStatus, UserRegistrDTO } from 'nswag-api/nswag-api-auth';
import { Status } from 'nswag-api/nswag-api-marathon';

export class User implements IUserRegistrDTO {
    fullName: string;
    countEnter?: number;
    pinfl?: string;
    passportSeria?: string;
    passportNumber?: string;
    passportGiven?: string;
    passportDateBegin?: string;
    passportDateEnd?: string;
    birthDate: string;
    spNationId?: number;
    spCitizenshipId?: number;
    citizenship?: string;
    spCountryId?: number;
    spRegionId?: number;
    spDistrictId?: number;
    address?: string;
    spSexId?: number;
    addressBirth?: string;
    phoneMain: string;
    phoneAdditional?: string;
    lockoutEnabled: boolean;
    isFromGCP: boolean;
    spDepartmentId?: number;
    hospitalInn?: number;
    athletesId: number;
    specId?: number;
    imageFileGuid: string;
    applicationUserId?: string;
    spUserTypeId?: number;
    isForeign: boolean;
    isPassportUzb: boolean;
    rolesStr: string;
    staffId?: number;
    mainPositionId?: number;
    id: string;
    userId: string;
    name: string;
    email: string;
    avatar?: string;
    status?: string;
    userName: string;
    fio: string;
    mainRole: string;
    roles: string[];
    dateLastEnter: string;
    userAdd: string;
    dateLastActive: string;
    surname: string;
    patronymic: string;
    token?: string;
    isChangePassword: boolean;
    password: string;
    passwordS: string;
    passwordOld: string;
    positions: any;
    spInstitutionId: number;
    spInstitution: string;
    spInstitutionName: string;
    tbStaffId: string;
    tbStaffFIO: string;
    imageFileId?: string;
    tbFileImageBase64: string;
    expiration: Date;
    spInstitutionTin: number;
    branchId?: number;
    userApplicationStatus: UserApplicationStatus;
    workPlaceCommit?: string | undefined;
    erPsportDTO?: ERPsportDTO | undefined;
    organization?: OrganizationDTO | undefined;
}
